- name: 'Upload rhcos image to glance'
  command:
    cmd: "openstack image create --container-format=bare --disk-format=qcow2 --file {{ rhcos_osp_file }} {{ rhcos_image }}"
  when: False
  tags: rhcos_image

- name: 'Upload rhcos image to glance'
  openstack.cloud.image:
    name: "{{ rhcos_image }}"
    container_format: bare
    disk_format: qcow2
    state: present
    filename: "{{ rhcos_osp_file }}"
  tags: rhcos_image
