- name: Compute vars specific to current installation
  set_fact:
    # User-provided values
    os_subnet_range: "{{ machine_network }}"
    os_flavor_master: "{{ osp_master_flavor }}"
    os_flavor_worker: "{{ osp_compute_flavor }}"
    os_image_rhcos: "{{ rhcos_image }}"
    # Service subnet cidr
    svc_subnet_range: '172.30.0.0/16'
    os_svc_network_range: '172.30.0.0/15'
    # Subnet pool prefixes
    cluster_network_cidrs: '10.128.0.0/14'
    # Subnet pool prefix length
    host_prefix: '23'
    # Name of the SDN.
    # Possible values are OpenshiftSDN or Kuryr.
    os_networking_type: "{{ network_type }}"
  
    # Number of provisioned Control Plane nodes
    # 3 is the minimum number for a fully-functional cluster.
    os_cp_nodes_number: 3
  
    # Number of provisioned Compute nodes.
    # 3 is the minimum number for a fully-functional cluster.
    os_compute_nodes_number: 3
  
    # The public network, if available. Required for os_api_fip and
    # os_ingress_fip.
    # If non-empty, an additional floating IP will be created and attached to
    # the bootstrap machine to allow the retrieval of a log bundle in case of
    # install failure ('must-gather').
    os_external_network: '{{ osp_external_network }}'
  
    # OpenShift API floating IP address. If this value is non-empty, the
    # corresponding floating IP will be attached to the Control Plane to
    # serve the OpenShift API.
    os_api_fip: '10.206.31.125'
  
    # OpenShift Ingress floating IP address. If this value is non-empty, the
    # corresponding floating IP will be attached to the worker nodes to serve
    # the applications.
    os_ingress_fip: '10.206.31.34'
